"""Add tool_execution table and update relations

Revision ID: 430e3bc13741
Revises: de990369e21c
Create Date: 2025-10-30 01:38:38.207943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '430e3bc13741'
down_revision: Union[str, Sequence[str], None] = 'de990369e21c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.drop_table('_prisma_migrations')
    op.alter_column('Invalidated_tokens', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_Invalidated_tokens_id'), 'Invalidated_tokens', ['id'], unique=False)
    op.alter_column('Scan', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Scan', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Scan', 'target',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Scan', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Scan', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Scan', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Scan', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_index(op.f('Scan_userId_idx'), table_name='Scan')
    op.create_index(op.f('ix_Scan_id'), 'Scan', ['id'], unique=False)
    op.create_index(op.f('ix_Scan_userId'), 'Scan', ['userId'], unique=False)
    op.drop_constraint(op.f('Scan_userId_fkey'), 'Scan', type_='foreignkey')
    op.create_foreign_key(None, 'Scan', 'User', ['userId'], ['id'])
    op.alter_column('ScanFile', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ScanFile', 'toolExecutionId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ScanFile', 'fileName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ScanFile', 'gcsPath',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ScanFile', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ScanFile_gcsPath_key'), table_name='ScanFile')
    op.drop_index(op.f('ScanFile_toolExecutionId_idx'), table_name='ScanFile')
    op.create_index(op.f('ix_ScanFile_id'), 'ScanFile', ['id'], unique=False)
    op.create_index(op.f('ix_ScanFile_toolExecutionId'), 'ScanFile', ['toolExecutionId'], unique=False)
    op.create_unique_constraint(None, 'ScanFile', ['gcsPath'])
    op.drop_constraint(op.f('ScanFile_toolExecutionId_fkey'), 'ScanFile', type_='foreignkey')
    op.create_foreign_key(None, 'ScanFile', 'ToolExecution', ['toolExecutionId'], ['id'])
    op.alter_column('ToolExecution', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ToolExecution', 'scanId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ToolExecution', 'toolName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ToolExecution', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ToolExecution', 'startTime',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('ToolExecution', 'endTime',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('ToolExecution', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ToolExecution_scanId_idx'), table_name='ToolExecution')
    op.create_index(op.f('ix_ToolExecution_id'), 'ToolExecution', ['id'], unique=False)
    op.create_index(op.f('ix_ToolExecution_scanId'), 'ToolExecution', ['scanId'], unique=False)
    op.drop_constraint(op.f('ToolExecution_scanId_fkey'), 'ToolExecution', type_='foreignkey')
    op.create_foreign_key(None, 'ToolExecution', 'Scan', ['scanId'], ['id'])
    op.alter_column('User', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('User', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('User', 'image',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('User_email_key'), table_name='User')
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.create_index(op.f('User_email_key'), 'User', ['email'], unique=True)
    op.alter_column('User', 'image',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('User', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('User', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('User', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'ToolExecution', type_='foreignkey')
    op.create_foreign_key(op.f('ToolExecution_scanId_fkey'), 'ToolExecution', 'Scan', ['scanId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_ToolExecution_scanId'), table_name='ToolExecution')
    op.drop_index(op.f('ix_ToolExecution_id'), table_name='ToolExecution')
    op.create_index(op.f('ToolExecution_scanId_idx'), 'ToolExecution', ['scanId'], unique=False)
    op.alter_column('ToolExecution', 'createdAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ToolExecution', 'endTime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=True)
    op.alter_column('ToolExecution', 'startTime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=True)
    op.alter_column('ToolExecution', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ToolExecution', 'toolName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ToolExecution', 'scanId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ToolExecution', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'ScanFile', type_='foreignkey')
    op.create_foreign_key(op.f('ScanFile_toolExecutionId_fkey'), 'ScanFile', 'ToolExecution', ['toolExecutionId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(None, 'ScanFile', type_='unique')
    op.drop_index(op.f('ix_ScanFile_toolExecutionId'), table_name='ScanFile')
    op.drop_index(op.f('ix_ScanFile_id'), table_name='ScanFile')
    op.create_index(op.f('ScanFile_toolExecutionId_idx'), 'ScanFile', ['toolExecutionId'], unique=False)
    op.create_index(op.f('ScanFile_gcsPath_key'), 'ScanFile', ['gcsPath'], unique=True)
    op.alter_column('ScanFile', 'createdAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ScanFile', 'gcsPath',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ScanFile', 'fileName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ScanFile', 'toolExecutionId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ScanFile', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'Scan', type_='foreignkey')
    op.create_foreign_key(op.f('Scan_userId_fkey'), 'Scan', 'User', ['userId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_Scan_userId'), table_name='Scan')
    op.drop_index(op.f('ix_Scan_id'), table_name='Scan')
    op.create_index(op.f('Scan_userId_idx'), 'Scan', ['userId'], unique=False)
    op.alter_column('Scan', 'updatedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               nullable=False)
    op.alter_column('Scan', 'createdAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Scan', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Scan', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Scan', 'target',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Scan', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Scan', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_Invalidated_tokens_id'), table_name='Invalidated_tokens')
    op.alter_column('Invalidated_tokens', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
